piVersion: argoproj.io/v1
kind: Application
metadata:
  name: mongodb
  namespace: argocd  
spec:
  destination:
    namespace: default  
    server: https://kubernetes.default.svc
  source:
    repoURL: 'oci://registry-1.docker.io/bitnamicharts/mongodb'
    chart: mongodb
    targetRevision: 13.0.1  
    helm:
      valueFiles:
        - path: mongo-values.yaml  
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true